export const GUIDE_SECTIONS = [
  {
    id: "face",
    title: "票面与品相",
    intro: "先认票本身：背面有没有胶、四周怎么撕开、新的还是用过的、伤在哪里。",
    entries: [
      {
        id: "gum",
        title: "背胶",
        body: "邮票背面刷的一层胶，用来贴上信封。没使用过的新票，常见「原胶」：胶面均匀，没有被洗过。旧票若用温水揭下来，胶会变薄、发花，甚至完全无胶。",
        note: "不要把带胶的新票泡进水里「洗干净」，胶遇水会粘连、发皱。也不要用胶带或胶水直接粘票。",
      },
      {
        id: "perf",
        title: "齿孔",
        body: "印厂在票与票之间打出一排小孔，方便撕开。齿孔度数是 2 厘米里有多少个孔，例如 11½、12½；上下和左右不同时写成 11½×11。还有线齿、点线齿，以及故意不打孔的无齿票。",
        note: "撕票沿线孔走，硬扯会缺齿。交换时若有缺齿、齿孔拉长，提前写在备注里。",
      },
      {
        id: "mint-used",
        title: "新票 / 旧票",
        body: "新票是还没拿去付过邮资的，通常带着背胶。旧票是贴上信封、走过邮路的。旧票不一定比新票「差」，很多人专门集实寄。邮邻交换时，双方先说清要新还是旧。",
        note: "别默认只有新票才值得留下。邮邻不谈涨跌，只谈你想不想要这枚。",
      },
      {
        id: "cto",
        title: "信销 / 盖销",
        body: "信销是贴在实寄邮件上、经邮局盖戳销票。盖销多是集邮处或经销商成批盖戳，票没有真正走过邮路，背面常常还留着胶。",
        note: "盖销票有时看起来「又新又有戳」，不要把它当成信销。",
      },
      {
        id: "condition",
        title: "品相常见伤",
        body: "揭薄是揭票时把纸纤维带掉一层。此外还有折痕、污渍、缺齿、褪色、齿孔被拉长。交换前不妨对着光看一看纸是否均匀。",
        note: "有伤的票仍可标成「可换」，但备注里写清楚，别等对方收到才发现。",
      },
    ],
  },
  {
    id: "format",
    title: "版式",
    intro: "同一套票可以是整版、小版、小型张或小本。名字很像，指的不是同一件事。",
    entries: [
      {
        id: "full-sheet",
        title: "大版（全张）",
        body: "印刷厂一次印出的整张，上面整齐排着多枚邮票，四周常有边纸、色标、版号和厂名。整版占地大，日常交换更多是从大版上沿齿孔撕下的单枚。",
        note: "从大版上撕票时沿齿孔，别伤到邻票。整版缺了一角再补，就不算完整大版了。",
      },
      {
        id: "mini-pane",
        title: "小版（小版张）",
        body: "专门设计成较小规格发行的版张，枚数少，边纸上常有图案或文字。它是一种正式发行规格，不是从大版上随便裁下来的一块。九十年代以来更常见。",
        note: "把大版上撕下的「几枚连在一起」叫做小版，会让对方误解。",
      },
      {
        id: "souvenir",
        title: "小型张",
        body: "单独设计的一张小纸，通常只印一枚邮票（也有少数多枚），四周宽边常带图画或说明。小型张本身就是一个完整的收藏单位。",
        note: "不要把小型张的边纸裁掉，边纸是它的一部分。",
      },
      {
        id: "set-sheet",
        title: "小全张",
        body: "把一套里的各枚印在同一张纸上，一次拿齐整套。它强调「一套同纸」：和小版张（较小的版式）、小型张（常一枚一纸）都不同。",
        note: "小全张、小型张、小版张名字接近，交换时写全称，或附一张照片。",
      },
      {
        id: "booklet",
        title: "小本票",
        body: "把邮票装订成小本，方便随身使用。封面、过桥（本内连接票的空白纸）都是组成部分，有的过桥两侧齿孔比较特殊。",
        note: "拆本零售会让「完整小本」不再完整。若你只集单枚，说清楚「拆自小本」。",
      },
      {
        id: "block",
        title: "连票 / 四方连",
        body: "两枚以上仍连在一起：横双连、直双连、四方连（2×2）。连票看的是「没撕开」这件事，图案是否相同倒在其次。",
        note: "一旦撕开就只是单枚。交换连票时不要先拆开「方便寄」。",
      },
    ],
  },
  {
    id: "numbering",
    title: "新中国志号",
    intro: "新中国邮票多数自带编号。先分清老纪特、文票与编号票、J/T、编年，查缺和交换会省事很多。",
    entries: [
      {
        id: "catalog-no",
        title: "志号是什么",
        body: "印在票面上的编号，用来准确指认是哪一套、哪一枚。交换时先报志号，比只说「那张猴票」清楚。可到目录页用 StampDIR 或大众邮藏核对。",
        note: "同题材会反复出票，生肖尤其如此。没有志号，很容易对错套。",
      },
      {
        id: "lao-jite",
        title: "老纪特",
        body: "大约 1949 年到 1967 年，纪念邮票标「纪」、特种邮票标「特」，如纪1、特1。集邮界把这一段习惯叫「老纪特」，和后来的 J/T、编年不是同一套编号。",
        note: "「老纪特」不是某一套的名字，而是一整段时期的统称。",
      },
      {
        id: "wenge",
        title: "文票 / 编号票",
        body: "纪特字头停用之后，大约 1967–1970 年有一批票被目录称为文票；1970–1973 年票面改印阿拉伯数字编号，称编号票。这是编号方式的过渡，不是另一家邮局。",
        note: "文票、编号票的目录排列和票面文字不一定一致，核对时以目录志号为准。",
      },
      {
        id: "jt",
        title: "J 票 / T 票",
        body: "1974 年到 1991 年，纪念票用 J、特种票用 T，后面跟序号，如 J.1、T.46（1980 年生肖猴）。这是老纪特之后、编年之前的一段。",
        note: "J/T 的序号按种类分别累计，不是按年份。T.46 不是 1946 年的票。",
      },
      {
        id: "biannian",
        title: "编年票",
        body: "1992 年起不再用 J/T，改成「年份–序号」，如 1992-1。一年里的纪念、特种都编进这条年号序列。现在大家说的「编年」，多指这一阶段。",
        note: "编年号看的是发行年份。对不上票名时，回到目录按年查，不要靠农历生肖的口头叫法硬猜。",
      },
      {
        id: "definitive",
        title: "普通邮票（普票）",
        body: "长期供应、多种面值、用来日常贴信的票，志号常带「普」。普票会再版、换纸、换齿孔，同一图案可能有多个版本。它和一年一套的纪特、编年不是一条收集线。",
        note: "只按图认普票不够，还要看志号和版次。",
      },
      {
        id: "personalized",
        title: "个性化 / 贺年专用等",
        body: "除了纪特和编年，还有个性化服务专用邮票、贺年专用邮票、贺卡专用邮票等，也是邮政正式发行，但收集口径和套票纪特不完全一样。",
        note: "把个性化票和同年编年套票混成「一套」，对方可能不认。交换时写明种类。",
      },
    ],
  },
  {
    id: "start",
    title: "开始集邮",
    intro: "认完名词之后，剩下的是怎么收、怎么说。邮邻不做鉴定，也不报行情。",
    entries: [
      {
        id: "face-value",
        title: "面值",
        body: "票面印的邮资金额，是寄信时付给邮局的价钱。收藏圈子里的谈价是另一回事。邮邻不报行情、不评估票价，面值只用来辨认这枚票。",
        note: "高面值不等于「更好」，低面值也不等于可以随便处理。",
      },
      {
        id: "set",
        title: "套票",
        body: "一次发行、同一主题的一组票，枚数在发行时就定好。缺一枚就叫不成套。交换时说清是整套还是单枚。",
        note: "不要把同题材、不同年份的票自行拼成一套。",
      },
      {
        id: "reprint",
        title: "再版 / 原版",
        body: "同一图案后来又印过，叫再版；第一次印的叫原版。早期普票、部分纪特都有再版，纸、齿孔、颜色会有差别。",
        note: "只看图案会把再版当原版。吃不准就在备注里写「版别未核」。",
      },
      {
        id: "margin",
        title: "边纸 / 厂铭",
        body: "票四周多出来的白边是边纸；边上印的厂名、版号、色标叫厂铭或版铭。带边、带厂铭的单枚和裁齐的「光票」不是同一种说法。",
        note: "裁掉边纸无法复原。若对方要带厂铭，不要先裁齐再寄。",
      },
      {
        id: "storage",
        title: "护邮袋与插册",
        body: "单枚请进透明护邮袋，再插入邮册。不要用普通透明胶带、胶水，或会粘胶的劣质塑料。有背胶的新票尤其怕热、怕潮、怕压。",
        note: "有些廉价相册的纸页会把背胶粘掉。与其「贴得整整齐齐」，不如让票待在袋子里。",
      },
      {
        id: "watermark",
        title: "水印 / 纸质",
        body: "有的纸在对光时能看到水印，纸的薄厚、纤维也不尽相同。入门只需知道：同样图案有时靠纸和水印才能分清版别。",
        note: "不要用液体或火来「显水印」。新手先学会查目录，鉴定是后话。",
      },
      {
        id: "how-to-start",
        title: "怎么开始集",
        body: "可以从一个国家、一个专题（生肖、建筑、鸟），或按编年逐年集起。先集自己能看懂、也喜欢看的票，不必追求「集全中国」。复品拿来交换，缺的标成想要。",
        note: "一上来按目录从纪1收到今年，很容易累。邮邻适合从手上已有的票开始登记。",
      },
      {
        id: "describe",
        title: "交换时怎么描述一枚票",
        body: "建议按这个顺序写：志号、票名、新票还是旧票、品相（有无揭薄、缺齿、折痕）、是否带边纸或厂铭。写在邮册备注和晒票里，对方少猜一轮。",
        note: "只发一张模糊图、不写志号，匹配很难发生。",
      },
    ],
  },
];

export const GUIDE_SECTIONS_EN = [
  {
    id: "face",
    title: "The stamp and its condition",
    intro: "Start with the piece itself: gum on the back, how the edges were separated, mint or used, and where it is damaged.",
    entries: [
      {
        id: "gum",
        title: "Gum",
        body: "The adhesive brushed on the back so the stamp can be stuck to an envelope. An unused mint stamp often has original gum: even, not washed. If a used stamp was soaked off in warm water, the gum thins, mottles, or disappears.",
        note: "Do not soak a mint stamp “to clean it” — gum clumps and wrinkles in water. Do not mount stamps with tape or glue.",
      },
      {
        id: "perf",
        title: "Perforation",
        body: "The printer punches a row of holes between stamps so they tear apart. Gauge is how many holes fall in 2 cm, e.g. 11½ or 12½; if vertical and horizontal differ, write 11½×11. There are also roulette and pin-perf issues, and imperforate stamps issued without holes on purpose.",
        note: "Tear along the holes; yanking pulls perfs. If a swap copy has short or elongated perfs, say so in the note.",
      },
      {
        id: "mint-used",
        title: "Mint / used",
        body: "Mint has not paid postage and usually still has gum. Used has been on mail. Used is not “worse”; many people collect covers. On Youlin, say whether you want mint or used before you swap.",
        note: "Do not assume only mint is worth keeping. Youlin does not talk prices — only whether you want this copy.",
      },
      {
        id: "cto",
        title: "Postal cancel / CTO",
        body: "A postal cancel is struck on mail that actually travelled. CTO (cancelled to order) is often done in bulk at a philatelic counter; the stamp never went through the post and often still has gum.",
        note: "A CTO copy can look “mint with a cancel”. Do not call it postally used.",
      },
      {
        id: "condition",
        title: "Common faults",
        body: "A thin is a layer of fibres lifted when the stamp was soaked. There are also creases, stains, short perfs, fading, and elongated holes. Hold it to the light before you swap and see whether the paper is even.",
        note: "A faulty copy can still be marked for swap, but write the fault in the note. Do not let the other person find it on arrival.",
      },
    ],
  },
  {
    id: "format",
    title: "Formats",
    intro: "The same issue can be a full sheet, a mini-pane, a souvenir sheet or a booklet. The names look alike; they are not the same thing.",
    entries: [
      {
        id: "full-sheet",
        title: "Full sheet",
        body: "The printer’s whole sheet, stamps in rows, often with selvedge, colour bars, plate numbers and the printer’s name. Sheets take space; everyday swaps are usually singles torn along the perfs.",
        note: "Tear along the holes and do not damage the neighbour. A sheet with a corner missing is no longer a complete sheet.",
      },
      {
        id: "mini-pane",
        title: "Mini-pane",
        body: "A sheet issued in a smaller format, with fewer stamps and often a design or text in the margin. It is an official format, not a piece cut from a full sheet. More common from the 1990s on.",
        note: "Calling a few stamps still joined from a full sheet a mini-pane will mislead the other person.",
      },
      {
        id: "souvenir",
        title: "Souvenir sheet",
        body: "A small sheet designed on its own, usually one stamp (sometimes more), with a wide pictorial or inscribed margin. The sheet is a collecting unit by itself.",
        note: "Do not trim the margin. The margin is part of the sheet.",
      },
      {
        id: "set-sheet",
        title: "Set sheet (xiaoquantzhang)",
        body: "Every value of a set printed on one piece of paper, so the set comes complete. It means “the set on one paper”, unlike a mini-pane (a smaller sheet format) or a souvenir sheet (often one stamp on one paper).",
        note: "The Chinese names for set sheet, souvenir sheet and mini-pane sit close together. Write the full name, or attach a photo.",
      },
      {
        id: "booklet",
        title: "Booklet",
        body: "Stamps bound into a small book for the pocket. Cover and interleaves (the blank paper joining the stamps) are part of it; some interleaves have unusual perfs on both sides.",
        note: "Breaking a booklet for singles ends the “complete booklet”. If you only collect singles, say “from a booklet”.",
      },
      {
        id: "block",
        title: "Multiple / block of four",
        body: "Two or more stamps still joined: horizontal pair, vertical pair, block of four (2×2). What matters is that they were not torn apart, whether the designs match or not.",
        note: "Once torn, they are singles. Do not split a multiple “to make mailing easier”.",
      },
    ],
  },
  {
    id: "numbering",
    title: "PRC catalogue numbers",
    intro: "Most PRC stamps carry a number on the face. Knowing the older Ji/Te series, the Cultural Revolution and serial issues, J/T, and year-serial numbers saves a lot of matching.",
    entries: [
      {
        id: "catalog-no",
        title: "What a catalogue number is",
        body: "The number printed on the stamp, identifying the set and the value. Quote it first in a swap; “that monkey stamp” is not enough. Check StampDIR or PostalWiki from the catalogues page.",
        note: "The same theme is reissued, New Year stamps especially. Without a number it is easy to match the wrong set.",
      },
      {
        id: "lao-jite",
        title: "Older Ji / Te",
        body: "Roughly 1949–1967, commemoratives were marked 纪 (Ji) and specials 特 (Te), e.g. Ji 1, Te 1. Collectors call this span the older Ji/Te period. It is not the same numbering as later J/T or year-serial issues.",
        note: "“Older Ji/Te” is a period name, not the name of one set.",
      },
      {
        id: "wenge",
        title: "Wen issues / serial numbers",
        body: "After the Ji/Te prefixes stopped, catalogues call a 1967–1970 group the Wen issues; from 1970–1973 the face shows Arabic serial numbers. This is a change of numbering, not another post office.",
        note: "Catalogue order and the words on the stamp may not match. Trust the catalogue number when you check.",
      },
      {
        id: "jt",
        title: "J / T issues",
        body: "From 1974 to 1991, commemoratives used J and specials T, plus a serial, e.g. J.1, T.46 (the 1980 Year of the Monkey). This sits after older Ji/Te and before year-serial numbering.",
        note: "J and T serials run separately, not by year. T.46 is not a 1946 stamp.",
      },
      {
        id: "biannian",
        title: "Year-serial issues",
        body: "From 1992, J/T stopped. Numbers became year–serial, e.g. 1992-1. Commemoratives and specials of that year share the sequence. “Year issues” usually means this period.",
        note: "The number is the year of issue. If the name does not match, look the year up in a catalogue; do not guess from the lunar animal’s nickname.",
      },
      {
        id: "definitive",
        title: "Definitives",
        body: "Long-running, many values, for ordinary postage. Numbers often include 普 (Pu). Definitives are reprinted, on new paper, with new perfs; the same design can have several versions. They are not the same collecting line as a year’s commemoratives.",
        note: "Matching a definitive by design is not enough. Check the number and the printing.",
      },
      {
        id: "personalized",
        title: "Personalised / New Year specials",
        body: "Besides commemoratives and year issues there are personalised service stamps, New Year specials, greeting-card stamps and so on. They are official issues, but they are not collected as ordinary commemorative sets.",
        note: "Bundling a personalised stamp with that year’s commemorative set as “one set” may not be accepted. Name the kind when you swap.",
      },
    ],
  },
  {
    id: "start",
    title: "Starting a collection",
    intro: "Once the words are clear, what remains is how you keep stamps and how you describe them. Youlin does not expertise and does not quote prices.",
    entries: [
      {
        id: "face-value",
        title: "Face value",
        body: "The postage printed on the stamp — what the post office charged to carry a letter. Market talk among collectors is a different matter. Youlin does not quote prices or value stamps; face value is only for identifying the piece.",
        note: "A high face value is not “better”, and a low one is not something to throw away.",
      },
      {
        id: "set",
        title: "Set",
        body: "A group issued together on one theme, with a fixed number of stamps. Missing one means the set is incomplete. Say whether you are swapping a whole set or a single.",
        note: "Do not assemble stamps of the same theme from different years and call them a set.",
      },
      {
        id: "reprint",
        title: "Reprint / original",
        body: "The same design printed again is a reprint; the first printing is the original. Early definitives and some commemoratives were reprinted, with differences in paper, perforation and colour.",
        note: "Looking only at the design will take a reprint for an original. If unsure, write “printing not checked” in the note.",
      },
      {
        id: "margin",
        title: "Selvedge / imprint",
        body: "The extra white paper around a stamp is selvedge; printer’s name, plate number and colour bars in the margin are the imprint. A copy with margin or imprint is not the same as a trimmed “copy without margin”.",
        note: "Trimmed selvedge cannot be put back. If they want an imprint, do not trim it before you mail.",
      },
      {
        id: "storage",
        title: "Mounts and stockbooks",
        body: "Singles go in clear mounts, then into an album. Do not use household tape, glue, or cheap plastic that sticks. Mint stamps with gum especially dislike heat, damp and pressure.",
        note: "Some cheap album pages will lift the gum. Better that the stamp stays in a mount than that it looks “neatly stuck down”.",
      },
      {
        id: "watermark",
        title: "Watermark / paper",
        body: "Some paper shows a watermark against the light; thickness and fibres also vary. For a beginner it is enough to know that the same design is sometimes told apart only by paper and watermark.",
        note: "Do not use liquid or flame to “bring up” a watermark. Learn to use a catalogue first; expertising comes later.",
      },
      {
        id: "how-to-start",
        title: "How to start collecting",
        body: "You can collect one country, one theme (New Year, buildings, birds), or year by year. Start with stamps you understand and like looking at; you need not “complete China”. Duplicates go for swap; missing ones are wants.",
        note: "Trying to collect every PRC issue from Ji 1 to this year is a fast way to tire. Youlin is built for registering what you already hold.",
      },
      {
        id: "describe",
        title: "How to describe a stamp in a swap",
        body: "A useful order: catalogue number, name, mint or used, condition (thin, short perfs, crease), and whether selvedge or imprint is present. Write it in the album note and the post so the other person guesses less.",
        note: "A blurry photo and no number make a match unlikely.",
      },
    ],
  },
];
